services:
    SoftDevel\OrgChartBundle\Factory\ChartFactory:
        arguments: ["@doctrine.orm.entity_manager"]

    SoftDevel\OrgChartBundle\Factory\ChartFactoryInterface:
        alias: 'SoftDevel\OrgChartBundle\Factory\ChartFactory'

    SoftDevel\OrgChartBundle\Twig\ChartExtension:
        arguments: ["@twig", "@form.factory"]
        tags:
            - { name: twig.extension }